### ISSUE TITLE
[BUG] pagination nzPageIndex double binding not work.

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#107]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

pagination nzPageIndex double binding not work.

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Renhj90520** [comment]
I bind nzPageIndex to a variable named currentPage, first I execute currentPage++ then request server after response I set nzTotal to the new value but not set currentPage to the new value (because they are the same), this situation nzPageIndex double binding doesn't work.  I have to set currentPage once more after setting nzTotal. this took me some time to solve. The version of ng-zorro is 0.7.1, I have no idea whether the lastest version has the same problem. @vthinkxie

**Comment by vthinkxie** [comment]
@Renhj90520 please submit a new issue with repro link.
