### ISSUE TITLE
table nzPageIndexChange 放到 nzPageIndex之前 _current不对

### ISSUE THREAD

**Issue by dyh333** [NG-ZORRO/ng-zorro-antd#1240]
## Version

0.6.15

## Environment

windows10, node8.x

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-vkcv1b](https://stackblitz.com/edit/ng-zorro-antd-setup-vkcv1b)

## Steps to reproduce

1. <nz-table #nzTable [nzAjaxData]="_dataSet" nzShowSizeChanger [nzLoading]="_loading" [nzTotal]="_total" 
 (nzPageIndexChange)="refreshData()" [(nzPageIndex)]="_current" [(nzPageSize)]="_pageSize" (nzPageSizeChange)="refreshData(true)">
nzPageIndexChange 放在nzPageIndex之前；
2. 点击分页，第二页
3. console.log显示第二页的_current为1
4. 再点击分页，第一页
5. console.log显示第一页的_current为2

## What is expected?

console.log显示第二页的_current为2
console.log显示第一页的_current为1

## What is actually happening?

console.log显示第二页的_current为1
console.log显示第一页的_current为2

**Comment by vthinkxie** [comment]
https://zhuanlan.zhihu.com/p/34249433

**Comment by CodingYiyi** [comment]
@vthinkxie according to the  [，linked page](https://github.com/angular/angular/pull/21514),this issue had been fixed by Angular on version 6.0.0-beta.5. 
below is the document:
"Now the value and validity will be updated before the ngModelChange event is emitted, so the same setup will log the updated value.

onChange(ngModel: NgModel) {
console.log(ngModel.value); // will log updated value
}"
but I have update my angular version to 7.0.0 and the issue is still been there，I have to write ‘[(zPageIndex)]’ before '(nzPageIndexChange)'

**Comment by CodingYiyi** [comment]
[this page](https://github.com/angular/angular/issues/11234)will be helpful,It seems a angular bug.

**Comment by VEMTK** [comment]
...

**Comment by wulingfeng0529** [comment]
I have the same problem,
my angular version is 7.1.4
