### ISSUE TITLE
关于应用 NZ 响应表单的BUG

### ISSUE THREAD

**Issue by myepoch** [NG-ZORRO/ng-zorro-antd#134]
当文本框失去焦点的时候，预期文本框 不可编辑（但是disable 顺序在上起作用，disable顺序在下不起作用）
`  <form nz-form [formGroup]="validateForm" (ngSubmit)="_submitForm()">
<input id="email" name="email" formControlName="email" (blur)="onIdCardChange(validateForm.controls)" class="form-control">
  </form>`

`    ngOnInit() {
    this.validateForm = this.fb.group({ // 初始化表单模型
      email            : [ '', [ Validators.email ] ]
    });
  }

  public onIdCardChange (form: any): void { // 当页面文本框失去焦点时
    // this.validateForm.get ('email').disable (); // 如果写在这，那么文本框 disable 起作用

    this.validateForm = this.fb.group({
      email            : [ 'hello@nz-zorro.com', [ Validators.email ] ],
    });

    this.validateForm.get ('email').disable (); // 如果写在这，那么文本框 disable 不起作用
  }`

**Comment by vthinkxie** [comment]
bug confirm, thanks.

**Comment by vthinkxie** [comment]
@myepoch It seems that you are using original angular input form, it has noting todo with ng-zorro.

**Comment by deart1mer** [comment]
Hi. 
I think it should be a bug.
A custom form control with 'disabled' attribute should implement the `setDisabledState` method of interface `ControlValueAccessor` ', otherwise it can not be disabled when using a reactive form such as` FormControl` / `FormGroup`.

For example:
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/input/nz-input.component.ts

```js
export class NzInputComponent implements AfterContentInit, ControlValueAccessor {
  // ...

  // This function is called when the control status changes to or from "DISABLED".
  setDisabledState(isDisabled: boolean): void {
    this.nzDisabled = isDisabled;
  }
}
```

I search the components file. I found that many components are missing this hook.

**Comment by deart1mer** [comment]
If confirmed as a bug. My pleasure to help to fix other components that implement `ControlValueAccessor` to be a custom form control.

**Comment by vthinkxie** [comment]
@deart1mer Yes, nz-input and all other components such as nz-datepicker have not implement the setDisabledState yet, but this is not associate with this issue since @myepoch used input other than nz-input.

It is great that if you want to help us to patch all components with  setDisabledState, thanks.
