### ISSUE TITLE
why there are some styles for body when I open a modal？

### ISSUE THREAD

**Issue by cyhjojo** [NG-ZORRO/ng-zorro-antd#1516]
## What problem does this feature solve?

I found that when I open a modal ， the whole page will be offset. That's because the <body> of the page will add "padding-right: 17px; overflow: hidden;"  automatically. I cannot understand why add the padding !

## What does the proposed API look like?

I hope my pages don't shift when I open a modal.

**Comment by vthinkxie** [comment]
https://ng.ant.design/components/modal/zh 
does the page offset when you open the modal?

**Comment by cyhjojo** [comment]
@vthinkxie  No , but I found this is because that the official website has side scrollbar ， however ，some of my page have no one. And my nav's background is blue ,it'll be  very conspicuous，when it has a gap. What can I do for this?
ps: the official website also has a gap when I open the modal.

**Comment by vthinkxie** [comment]
![kapture 2018-05-24 at 16 56 58](https://user-images.githubusercontent.com/1506722/40475249-b3ae9faa-5f73-11e8-89da-d54746ef8181.gif)

and there is no padding if there is no scrollbar


https://stackblitz.com/edit/angular-oz4gth?file=app/app.component.ts

please provide minimal repro link if any problem.

**Comment by vthinkxie** [comment]
if there is no gap, the page will shake

**Comment by jskvoll** [comment]
in the case when we use `nz-layout ` (https://ng.ant.design/components/layout/en#components-layout-demo-fixed-sider) as main scroll container it just adds an extra gap, since we already have scroll inside `nz-layout `
![image](https://user-images.githubusercontent.com/1451730/40681934-893869dc-639b-11e8-8119-bff372c0f8fc.png)
![image](https://user-images.githubusercontent.com/1451730/40682007-c1255f44-639b-11e8-875d-db128a4de92a.png)

It would be awesome if it will be some kind of flag to not to use that behaviour,  or just fix slide container.

**Comment by ArthurMao** [comment]
try this :
```
body > ::-webkit-scrollbar {
        width: 0;
    }
```
