### ISSUE TITLE
nz-slider init value/set value not effect in component

### ISSUE THREAD

**Issue by yinjs** [NG-ZORRO/ng-zorro-antd#1529]
## Version

0.7.1

## Environment

ubuntu 17.10, chrome 63.0.3239.108, ng-zorro 0.7.1

## Reproduction link

[https://stackblitz.com/edit/ng-zorro-antd-setup-slc7aw](https://stackblitz.com/edit/ng-zorro-antd-setup-slc7aw)

## Steps to reproduce

add nz-slider in form. for more details please check stacklitz link

## What is expected?

nz-slider work in form, init value/set value effect in component

## What is actually happening?

nz-slider not work in form, init value/set value not effect in component

**Comment by dmytroyarmak** [comment]
@yinjs I've tested it as well, and, yes, you are right. An initial value is not rendered properly in the range component.

But the setting of new value works fine. In your example, it doesn't work because you have a typo in the name of init lifecycle method. Your example has `ngInit` instead of `ngOnInit`.

Here is StackBlitz that I've used to test:
https://stackblitz.com/edit/ng-zorro-antd-setup-s8g8m8
