### ISSUE TITLE
nzTooltip: tooltip would not expand according to its child element's width

### ISSUE THREAD

**Issue by wendzhue** [NG-ZORRO/ng-zorro-antd#1800]
## Version
1.1.1
## Environment
Universal
## Reproduction link
[https://stackblitz.com/edit/angular-m9vk7v?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-m9vk7v?file=src%2Fapp%2Fapp.component.ts)
## Steps to reproduce
Hover the text, and you can see the text exceeds the tooltip's boundary.
## What is expected?
The tooltip should expand to wrap its child component.
## What is actually happening?
The texts exceeds the tooltip's boundary.

**Comment by haoliangwu** [comment]
@wendzhue I met the same issue before but I don't think it is a bug because the .ant-tooltip class restrict the container max-width to 250px. You can figure out [here](https://github.com/NG-ZORRO/ng-zorro-antd/blob/b1ac85ca5b2acacbb57f9a388800991ede825cb6/components/style/themes/default.less#L274).

Just override the .ant-tooltip max-width property can solve this issue briefly.

**Comment by wendzhue** [comment]
@haoliangwu You are absolutely right. But in my opinion, it would be nice if ng-zorro could detect that `[nzTitle]` is a TemplateRef and remove the attribute automatically.

**Comment by yoyogis** [comment]
@haoliangwu override @tooltip-max-width: 250px;  will change all tooltip's in the application? Right? But I just want change one tooltip's width.
