### ISSUE TITLE
nzCheckbox and Checkbox Can not be used in safari  10.1.2 

### ISSUE THREAD

**Issue by zy-1995** [NG-ZORRO/ng-zorro-antd#254]
Although my browser has some minor problems, but I have seen the Checkbox  on <a>https://ant.design/components/checkbox-cn/</a>,that can be used

**Comment by HsuanXyz** [comment]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/22736418/30207030-c878ac82-9453-11e7-9b98-4a714f101bf6.png)
Normal work
![image](https://user-images.githubusercontent.com/22736418/30207111-ffb69466-9453-11e7-82ae-72a090bd7346.png)
Will trigger two clicks

## Expected behavior

https://ant.design/components/checkbox-cn/

## Minimal reproduction of the problem with instructions


## What is the motivation / use case for changing the behavior?

On your Mac(Safari), go to https://ng.ant.design/#/components/checkbox

## Environment

<pre><code>
Angular version: 4.3.3

ng-zorro-antd version: 0.5.0-rc.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [X] Safari (desktop) version 10.1.2 (12603.3.8)
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Mac

Others:

</code></pre>

**Comment by zy-1995** [comment]
@HsuanXyz thank you .The problem was initially found because it was not available in the "nz-demo-table-selection"

**Comment by vthinkxie** [comment]
confirm, thanks your feedback.
