### ISSUE TITLE
Cannot directly highlight or click elements in carousel

### ISSUE THREAD

**Issue by stephenasamoah** [NG-ZORRO/ng-zorro-antd#2631]
## Version
7.0.0-rc.1
## Environment
hmr, dev
## Reproduction link
[https://stackblitz.com/edit/ngantd-carousel-interactions](https://stackblitz.com/edit/ngantd-carousel-interactions)
## Steps to reproduce
I initialize the `nz-carousel` element and put in some HTML markup or `nz-input` element.
## What is expected?
I expect to be able to select or click any of the afore-mentioned elements with my mouse.
## What is actually happening?
Neither of those work. I can only interact or focus the input element using the keyboard's `Tab` key.

**Comment by wendzhue** [comment]
Because of this line:

https://github.com/NG-ZORRO/ng-zorro-antd/blob/46fbee5bb0f917fd532a2b15b5684e5e316c57ad/components/carousel/nz-carousel.component.html#L4

Four months ago a user reached to us that images cannot be scrolled in carousel, so I told him to make a pr for that. It seems now this should be removed.

**Comment by wendzhue** [comment]
@peterblazejewicz I guess this conflict is inevitable unless we introduce another option like `nzEnableKeyboardSlide`.
