### ISSUE TITLE
unexpected transition when router change

### ISSUE THREAD

**Issue by vthinkxie** [NG-ZORRO/ng-zorro-antd#2697]
https://stackblitz.com/edit/ng-zorro-antd-start-qgr95a?file=src%2Fapp%2Fhome%2Fhome.component.html

**Comment by blackraindrop** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-sbvjt5

**Comment by blackraindrop** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-nqwret 
把导航从路由组件移动到app.component不会闪烁。

**Comment by blackraindrop** [comment]
https://stackblitz.com/edit/ng-zorro-antd-start-sxbud9
使用router.navigate代替routerlink也不会闪烁

**Comment by vthinkxie** [comment]
transition error without ng-zorro-antd
https://stackblitz.com/edit/ng-zorro-antd-start-uvffqm?file=src%2Fapp%2Fapp.component.ts

**Comment by vthinkxie** [comment]
ref https://github.com/angular/material2/issues/14646

**Comment by trotyl** [comment]
For workaround, using imperative className assignment rather than class binding:

https://stackblitz.com/edit/ng-zorro-antd-start-jw8faq?file=src/app/app.component.ts

This is likely to be a Chrome issue triggered by specific timing, while not sure what the real cause, using a different sequence of actions may get rid of this issue.

**Comment by vthinkxie** [comment]
ref https://github.com/angular/angular/issues/34718
