### ISSUE TITLE
tree-select: 在节点前添加图标

### ISSUE THREAD

**Issue by margintopt** [NG-ZORRO/ng-zorro-antd#3330]
## What problem does this feature solve?
tree-select中使用的是tree tree组件支持'nzTreeTemplate'的ContentChild一个自定义模板或者nzShowIcon的api  但tree支持的这两个api都没有暴露给tree-select

## What does the proposed API look like?
将tree的可以在节点前添加图标的api暴露给tree-select

**Comment by matulef** [comment]
I want to be sure I understand this issue, since the translation isn't very clear:

The goal here is not just to add icons, but to be able to customize the nodes of the tree-select in the same way you can with a tree. You would do this using the #nzTreeTemplate reference, and just pass the template to the underlying tree component. The syntax would be similar to the example [here](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/tree/demo/directory.ts), just with a tree-select instead of a tree.
