### ISSUE TITLE
nzPrefixIcon in nz-input-group has a hardcoded style that brakes scss theme

### ISSUE THREAD

**Issue by Dimanoid** [NG-ZORRO/ng-zorro-antd#3950]
### Code link
[https://github.com/NG-ZORRO/ng-zorro-antd/blob/9499aec7972cb075dcf5a16bf8d72328d6bf930b/components/input/nz-input-group.component.html#L23](https://github.com/NG-ZORRO/ng-zorro-antd/blob/9499aec7972cb075dcf5a16bf8d72328d6bf930b/components/input/nz-input-group.component.html#L23)

### Steps to reproduce
nz-input-group.component.html
line 23 
<i nz-icon [nzType]="nzPrefixIcon" *ngIf="nzPrefixIcon" style="color: rgba(0, 0, 0, 0.25)"></i>

### What is expected?
nz-input-group should not to have hardcoded color style in template

### What is actually happening?
Icons color defined in theme.less is overridden by hardcoded style in nz-input-group template

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | any |

**Comment by wendzhue** [comment]
Yes. The reason why we wrote this is because antd doesn't provide this style in less files. See https://ant.design/components/input/#components-input-demo-presuffix.

![屏幕快照 2019-08-08 下午9 44 20](https://user-images.githubusercontent.com/12122021/62708303-b2554600-ba25-11e9-89c1-3d2dcf09af2a.png)

Could you please open a pull request there first? https://github.com/ant-design/ant-design
