### ISSUE TITLE
Enable strictTemplates

### ISSUE THREAD

**Issue by xiaoxiangmoe** [NG-ZORRO/ng-zorro-antd#4757]
https://angular.cn/guide/template-typecheck#strict-mode

**Comment by dylanvdmerwe** [comment]
We have this enabled in our project and Zorro library 9.0.1 causes many errors with strict checking enabled. Please can this be looked into so this can be enabled in our projects.

**Comment by Iyashu5040** [comment]
Please look into enabling this.

There are numerous issues when trying to build a project with the setting enabled.
Angular Version: 9.1.1
"ng-zorro-antd": "9.0.1"

Example Error:
NzSelect binding a templateRef to nzNotFoundContent throws: `Type 'TemplateRef<any>' is not assignable to type 'string'`. The docs at https://ng.ant.design/components/select/en specify that the type of nzNotFoundContent is `string | TemplateRef<void>` but I am unable to bind a template ref. This is because the type of nzNotFoundContent in node_modules is `nzNotFoundContent: string | undefined;`
