### ISSUE TITLE
锚点向上滚动时，偶尔会到顶部

### ISSUE THREAD

**Issue by kentTanL** [NG-ZORRO/ng-zorro-antd#477]
HI，下图中，黑色的是顶部栏，下面是文档的内容，大多数的时候，锚点都是在顶部栏下方，但是偶尔向上滚动时，会直接出现在顶部，即“top: 0px;”的样式没有被取消，不知是否有解决的方法？谢谢您们

![zorro](https://user-images.githubusercontent.com/15412193/31933041-8d336aa8-b8da-11e7-9c00-4818dcdfb1a3.png)

**Comment by vthinkxie** [comment]
@cipchk

**Comment by cipchk** [comment]
@kentTanL 能否利用 [plnkr](http://plnkr.co/edit/tpl:sKWy62) 提供一下你的实际使用条件，以便我更好的复现呢？非常感谢。

**Comment by cipchk** [comment]
@vthinkxie please assignee for me, thx.

**Comment by HsuanXyz** [comment]
@cipchk 



## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior


在使用 `nz-affix` 的情况下，在出现浮动后，使用滚轮快速滚到页面顶部，浮动依然存在。
![anchor](https://user-images.githubusercontent.com/22736418/32098919-d175f484-bb40-11e7-835a-34e2d7a33c19.gif)



## Expected behavior



## Minimal reproduction of the problem with instructions

https://ng.ant.design/#/other/anchor
## What is the motivation / use case for changing the behavior?



## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: 0.5.5

Browser:
- [ ] Chrome (desktop) Version 63.0.3239.18 (Official Build) dev (64-bit)
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cipchk** [comment]
@HsuanXyz i got it, thx.

**Comment by kentTanL** [comment]
@cipchk 没错，就是像@HsuanXyz所描述的那样。

非常抱歉，现在才回复
