### ISSUE TITLE
Close date-picker when new one is opened/focused

### ISSUE THREAD

**Issue by junekpavel** [NG-ZORRO/ng-zorro-antd#5342]
### Reproduction link
[https://codesandbox.io/s/wq3ow](https://codesandbox.io/s/wq3ow)

### Steps to reproduce
Happens when navigating form via keyboard when there are more date pickers at row. Just open first date picker, press tab (so the next one will be focused) and press enter (so the next one will be opened). But the previous opened date picker won't close. So there are two (or even more) pickers opened at the same time.

### What is expected?
When new date picker is opened (or just focused) the currently opened one should be closed.

### What is actually happening?
More date pickers are opened at the same time:
https://www.dropbox.com/s/6bcsw86h1xilcz6/ngzorro-datepicker.mov?dl=0

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome 83 |

**Comment by sainisagar310** [comment]
+1

Facing the same issue. When we have multiple date-pickers in a form so the next date-picker should open when it gets focused through tab key and the previous one should get closed.

Looking forward to getting it fixed in the next coming releases.

![NZ-ZORRO DatePicker Accessibility Issue](https://user-images.githubusercontent.com/26157513/85919986-889b4c80-b88d-11ea-9966-c257d7892e07.gif)

**Comment by wenqi73** [comment]
Has Supported this in 11.4.1
