### ISSUE TITLE
Button stays in active state

### ISSUE THREAD

**Issue by junekpavel** [NG-ZORRO/ng-zorro-antd#5344]
### Reproduction link
[https://codesandbox.io/s/sqm3y](https://codesandbox.io/s/sqm3y)

### Steps to reproduce
Click on any button. Button stays in active state after clicked, until user click outside (to any other element).

### What is expected?
Button shouldn't be in active state. It should look exactly same as it looked before user clicked on it.

### What is actually happening?
Button stays in active state (has slightly different background color).

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome 83 |

---
This looks weird especially when button is eg for opening modal (https://codesandbox.io/s/7rvpt). Because the button is in active state even after user close the modal.

**Comment by vthinkxie** [comment]
I think you are talking about https://developer.mozilla.org/en-US/docs/Web/CSS/:focus
it is the `:focus` class, it works as expected since it indeed won't change `until user click outside (to any other element).`

but I'm not sure if the restore strategy after user clicks the modal works as expected
cc @hsuanxyz

**Comment by hsuanxyz** [comment]
it is expected, when the modal is open the focus will be on the modal and when it's closed it will restore the focus opened before
