### ISSUE TITLE
nz-select nzSuffixIcon does't work in multiple mode.nz-select 在多选或者tag模式下,nzSuffixIcon以及下拉箭头消失.

### ISSUE THREAD

**Issue by leemove** [NG-ZORRO/ng-zorro-antd#5568]
### Reproduction link
[https://ng.ant.design/components/select/zh#components-select-demo-multiple](https://ng.ant.design/components/select/zh#components-select-demo-multiple)

### Steps to reproduce
无

### What is expected?
能正常显示suffixxIcon 下拉箭头等相关属性

### What is actually happening?
没有任何显示 8.x版本中均正常

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | any |

**Comment by leemove** [comment]
is it  feature or bug?
这是一个功能还是问题啊?
```html
 <nz-select-arrow
      *ngIf="nzShowArrow && nzMode === 'default'"
      [loading]="nzLoading"
      [search]="nzOpen && nzShowSearch"
      [suffixIcon]="nzSuffixIcon"
    ></nz-select-arrow>
```
[https://github.com/NG-ZORRO/ng-zorro-antd/blame/master/components/select/select.component.ts#L103](https://github.com/NG-ZORRO/ng-zorro-antd/blame/master/components/select/select.component.ts#L103)

**Comment by DepickereSven** [comment]
@leemove @vthinkxie I made a PR #5650 to fix this issue

**Comment by vthinkxie** [comment]
Hi @leemove @DepickereSven 
按照 ant  design 设计规范，在多选模式下是没有下拉箭头的，在 9.x 之后同步了 antd 4.x 的设计规范，因此多选箭头被移除了，这是在预期中的，不是一个bug

感谢关注

**Comment by DepickereSven** [comment]
@vthinkxie @leemove 

By ant-design are you referring to this library https://github.com/ant-design/ant-design/? 

Because when I look in their docs I find the following:

<img width="905" alt="Schermafbeelding 2020-09-15 om 11 51 16" src="https://user-images.githubusercontent.com/26543813/93195660-c8195c80-f749-11ea-8dd5-6a915532a3db.png">

So for multi-select and tags is by default on false. But it's possible to set the showArrow on true so you can see it.

Like you can see in the following example the icons work in multi and tag mode.

https://stackblitz.com/edit/react-vrppip?file=index.js

**Comment by vthinkxie** [comment]
ref #5575
