### ISSUE TITLE
nz-timeline-item class attribute removed version 9

### ISSUE THREAD

**Issue by KevinVG** [NG-ZORRO/ng-zorro-antd#5682]
### Reproduction link
[https://stackblitz.com/edit/angular-ixi7zb?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ixi7zb?file=src/app/app.component.ts)

### Steps to reproduce
Open stackblitz example

### What is expected?
In version 8, the "class" attribute of the "nz-timeline-item" was kept when rendering the element. 

### What is actually happening?
In version 9, the "class" of the element is removed. This way it is not possible to apply specific classes to the timeline item. We need this to overwrite the styling of the dot. 

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome |

**Comment by wendellhu95** [comment]
<img width="494" alt="截屏2020-08-15 下午1 26 56" src="https://user-images.githubusercontent.com/12122021/90305991-00374080-defb-11ea-9ddf-c873d7411d19.png">

Could you please specifiy which `nz-timeline-item` you were refering to? A picture showing the different wouuld be appreciated. Thank you <3

**Comment by wendellhu95** [comment]
Hi @KevinVG . This is a breaking change introduced in 9.x. 

In order to implement the reverse feature, we use `nz-timeline-item` just to capture user contents

https://github.com/NG-ZORRO/ng-zorro-antd/blob/8415a702552fe147495c7d699bc62c68bc68249a/components/timeline/timeline.component.ts#L68-L69

, and render them with `<li>`

https://github.com/NG-ZORRO/ng-zorro-antd/blob/8415a702552fe147495c7d699bc62c68bc68249a/components/timeline/timeline.component.ts#L54-L66

So, please overwrite your styling files. I assume that changing `nz-timeline-item` to `li.ant-timeline-item` is suitable.

**Comment by KevinVG** [comment]
Hello,

When every ant-timeline-item has the same style, this is possible. However, we use different styling on each nz-timeline-item so we need to pass something along. The stackblitz example was an abstract example, i've made two new examples that use our styling. Same code for both versions, V8 works, V9 doesn't.

V8: https://stackblitz.com/edit/angular-sf61nv?file=src/styles.scss
V9: https://stackblitz.com/edit/angular-ixi7zb-qxbvkx?file=src/app/app.component.ts

**Comment by rppig42** [comment]
@KevinVG 
As a workaround, I add some class within the content and then use `li.ant-timeline-item:has(.blue)` to customize the style.

Not an ideal solution but works.
