### ISSUE TITLE
The text in nzSelect can't be selected

### ISSUE THREAD

**Issue by ousc** [NG-ZORRO/ng-zorro-antd#5875]
### Reproduction link
[https://stackblitz.com/edit/angular-by9o4e?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-by9o4e?file=src/app/app.component.ts)

### Steps to reproduce
Enter something in the nzSelect component, and then select text in it with your mouse.

### What is expected?
We can select text to copy and other

### What is actually happening?
The text can't be selected.

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.0 |
| Browser | Google Chrome 85.0.4183.121 |

---
ant design for react：https://ant.design/components/select-cn/#components-select-demo-search.
This kind of operation is supported in Ant Design for React, and hope ng-zorro can just perform like it, I think this is a bug instead of a feature request ;
![QQ20201008-153832](https://user-images.githubusercontent.com/31619017/95429027-63ce6f00-097c-11eb-997f-672f9bff7e05.gif)

**Comment by wenqi73** [comment]
Related to #5061.

**Comment by aaaahoang123** [comment]
This problem is the same as my problem at #4259 

It's because of the cdk overlay is on the top layer and your input is under it.

Some work around here:

Add some style like this to styles.less:

.ant-select-single.ant-select-open nz-select-search {
  position: absolute;
  z-index: 1001;
}

or in the *.component.css if you want to use it as local style:

 ::ng-deep.ant-select-single.ant-select-open ::ng-deep nz-select-search {
  position: absolute;
  z-index: 1001;
}

These codes make your <input /> is on a higher layer than the overlay when it open, and you can copy, or paste on it.

**Comment by ousc** [comment]
Thanks! So why these codes are not added to the default style of ng-zorro?

**Comment by aaaahoang123** [comment]
> Thanks! So why these codes are not added to the default style of ng-zorro?

Because it  just resolved the problem of the nz-select component, with the 'default' mode (not tag or multi).

The real problem is the angular cdk overlay, some other issues, not just this, are happened because of it, and wenqi73 has linked you to where one of them happen. Use google translate to see what vthinkxie said in that post.

I think they're working to fix all the problem, so, just wait!

**Comment by ousc** [comment]
Thank you for your temporary solution, It worked! 
And for this solution, nz-select-clear also need adjust  z-index at the same time.

I have seen the 5061 problem. It is indeed better to remove the mask layer. We only need to add a monitoring event when you click on the component to be used. If the clicked position is not in the component area stopPropagation, and perform the close operation.

And I'm Chinese.大写的尴尬

**Comment by hsuanxyz** [comment]
close via https://github.com/NG-ZORRO/ng-zorro-antd/pull/5925
