### ISSUE TITLE
在popover中使用dropdown组件导致popover不按正常逻辑关闭

### ISSUE THREAD

**Issue by tirelyl** [NG-ZORRO/ng-zorro-antd#6177]
### Reproduction link
[https://stackblitz.com/edit/dropdown-in-popover-bug?file=src/app/app.component.ts](https://stackblitz.com/edit/dropdown-in-popover-bug?file=src/app/app.component.ts)

### Steps to reproduce
在popover中使用dropdown组件，点开dropdown组件后，通过clickoutside的方式关闭dropdown组件，会导致popover组件也被关闭，如图：
![popover-bug](https://user-images.githubusercontent.com/20921324/101748701-d89e6080-3b07-11eb-8c3d-efdb3d4127c7.gif)

### What is expected?
关闭popover中的dropdown组件不会导致popover被关闭

### What is actually happening?
关闭popover中的dropdown组件会导致popover被关闭

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.0 |
| Browser | chrome 版本 86.0.4240.198（正式版本） （64 位） |

---
使用场景为：popover中可能会有下拉列表（dropdown）来选择一些条目，现在的表现为选择过后，popover整个被关闭了

**Comment by wendellhu95** [comment]
@wenqi73 这个应该是去掉 mask 之后点击事件被 disaptch 所有浮层元素导致的，这个有通用的解决方法吗？

**Comment by wenqi73** [comment]
@wendellhu95 11 会加个`nzHasBackdrop` 配置项

**Comment by tirelyl** [comment]
> @wendellhu95 11 会加个`nzHasBackdrop` 配置项

11 大概进度还要多久呀~

**Comment by wendellhu95** [comment]
可关注我们的 milestone https://github.com/NG-ZORRO/ng-zorro-antd/milestone/7

**Comment by tirelyl** [comment]
#6064 这个pr能解决此问题吗

**Comment by suica** [comment]
Same problem. Will this be fixed in v10.x?

**Comment by maojj** [comment]
Same problem， please fix it in v10.x

**Comment by wenqi73** [comment]
Will fixed in 11.0, you can downgrade to 10.0.2 to avoid this if you use 10.x

**Comment by maojj** [comment]
> Will fixed in 11.0, you can downgrade to **10.0.2** to avoid this if you use 10.x

 Our projects are use for 10000+ users ， and every user cost 1+ hours per day。We have to upgrade ng-zorro carefully。 Maybe downgrade to 10.0.2 is a solution，but there are other problems.

1.  Some other bugs  fixed after 10.0.2，list in  https://ng.ant.design/docs/changelog/zh。 If I use 10.0.2 , those bugs will still exist.
2.  If this bug fix in 11.0, because 11.0 is a major update, it will have some breaking changes , or some new bugs. We have to wait to a stable version, 11.1.0 or  11.2.0.

So actually，We can not use 10.0.2 in my product environment。We have to wait for this bug fixed in 10.x, or wait for 11.1/11.2(not 11.0)
