### ISSUE TITLE
Change Detection - nzPageIndex parameter in nz-table 

### ISSUE THREAD

**Issue by merih-bb** [NG-ZORRO/ng-zorro-antd#7193]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-d9yhyx](https://stackblitz.com/edit/ng-zorro-antd-ivy-d9yhyx)

### Steps to reproduce
While the table page is in the 2nd index, I want to reload the table and go to the 1st step. However, even though I set the nzPageIndex parameter to 1, the 2nd index remains selected in the pagination.

### What is expected?
What is expected is that the change detection works and sets the page as the 1st index.

### What is actually happening?
Even though I set the nzPageIndex parameter to 1, the 2nd index remains selected in the pagination.

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.1.1 |
| Browser | Chrome 97 |

**Comment by souhailharrati** [comment]
To solve this problem  add (nzPageIndexChange) (nzPageIndexChange) = "pageIndex = $event"
https://stackblitz.com/edit/ng-zorro-antd-ivy-gs89m7

because all NG-ZORRO's components are running under OnPush mode, this means any mutate to the @Input() data won't trigger change detection, please use immutable way to update array or object.

**Comment by merih-bb** [comment]
@souhailharrati Thanks

**Comment by souhailharrati** [comment]
@merih-bb  you are welcome
