### ISSUE TITLE
[nz-datepicker]-bug, 日期选择器如果在浏览器窗口最右边, 会有部分时间选择不到

### ISSUE THREAD

**Issue by pxyi** [NG-ZORRO/ng-zorro-antd#755]
日期选择器如果在浏览器窗口最右边, 会有部分时间选择不到[bug效果图](http://image.beibeiyue.com/admin/PreShop/55477b18-7962-4723-b0de-d3402d820817.png)

**Comment by vthinkxie** [comment]
Hi @pxyi ,it is by design, the datepicker only has two default overlay position since it should be limited to the left side of the input.
https://github.com/NG-ZORRO/ng-zorro-antd/blob/b5e9aeebbe5ee9a4b2a12fb13c707eab83b9b53b/src/components/core/overlay/overlay-position-map.ts#L94
close now, you can reopen this issue if after 0.7.0 released

**Comment by zhhb** [comment]
0.7.x not fixed yet! But，you can fix this bug like this
`
// add nzOnOpenChange event handle 
(nzOnOpenChange)="onDateOpenChange()"
// in your component
onDateOpenChange(){
setTimeout(() => window.dispatchEvent(new Event('resize')));
}
`
