### ISSUE TITLE
Messages being split - unnaturally in Japanese

### ISSUE THREAD

**Issue by DepickereSven** [NG-ZORRO/ng-zorro-antd#7799]
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-9v7u7r?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-9v7u7r?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Create an NZ notification in Japanese, then type any sentence in Japanese.

### What is expected?
It is expected that a word in Japanese would be properly segmented and not be cut off mid-word when continuing on a new line when there is no space left in the notification box. Using the example in Stackblitz, the entire last word 日本語 should be in a new line instead of being cut off like: 

日本
語
or
日
本語

### What is actually happening?
The message in the notification is displayed on a new line, regardless of if it is in mid-word or not.

| Environment | Info |
|---|---|
| ng-zorro-antd | 15.0.0 |
| Browser | Edge/Firefox/Chrome |

**Comment by hullis** [comment]
https://stackblitz.com/edit/ng-zorro-antd-ivy-zngvdt?file=src/app/app.component.ts 

Hi @DepickereSven. Here is a modified version of your demo. The text wrapping is not determined by ng-zorro-antd but CSS. You can use `word-break: keep-all` to avoid break the word "日本語".

This issue will be closed since it has nothing to do with zorro.

**Comment by DepickereSven** [comment]
Thank you for explaining, I wasn't fully sure if it would be something zorro offers or not.
