### ISSUE TITLE
Modern UI design - Just like m3.material.io

### ISSUE THREAD

**Issue by bharatbamaniya** [NG-ZORRO/ng-zorro-antd#8358]
## What problem does this feature solve?
This will help to create web pages with a modern UI feel component, I like your component but it seems to be outdated UI (No offence)

## What does the proposed API look like?
You can get inspiration from https://m3.material.io/components

**Comment by ParsaArvanehPA** [comment]
Hi @bharatbamaniya 
Ng-zorro is the Angular implementation of a design system called [Ant](https://ant.design/). We are currently at Ant version 4, and will move to version 5 in the future.

You can check the [design](https://ant.design/docs/spec/introduce) section of Ant document to become more familiar with it.

As an implementation we are to follow the Ant design system rules; meaning the rules of material will never be applied in our library, since material in another design system and has an Angular UI implementation for its own called Angular material.

**Comment by bjs9527** [comment]
什么时候能更新到ant design 5规范，有具有的时间表吗？
